<?php


/**
 * This class defines the structure of the 'participacion' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/18/12 10:52:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ParticipacionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ParticipacionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('participacion');
		$this->setPhpName('Participacion');
		$this->setClassname('Participacion');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addForeignKey('PERSONAJE_ID', 'PersonajeId', 'INTEGER', 'personaje', 'ID', false, null, null);
		$this->addForeignKey('PELICULA_ID', 'PeliculaId', 'INTEGER', 'pelicula', 'ID', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Personaje', 'Personaje', RelationMap::MANY_TO_ONE, array('personaje_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Pelicula', 'Pelicula', RelationMap::MANY_TO_ONE, array('pelicula_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ParticipacionTableMap
