<?php


/**
 * This class defines the structure of the 'personaje' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/12/12 11:50:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PersonajeTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PersonajeTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('personaje');
		$this->setPhpName('Personaje');
		$this->setClassname('Personaje');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 255, null);
		$this->addColumn('SUMMARY', 'Summary', 'LONGVARCHAR', true, null, null);
		$this->addForeignKey('RAZA_ID', 'RazaId', 'INTEGER', 'raza', 'ID', true, null, null);
		$this->addColumn('PHOTO', 'Photo', 'VARCHAR', true, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Raza', 'Raza', RelationMap::MANY_TO_ONE, array('raza_id' => 'id', ), null, null);
    $this->addRelation('Participacion', 'Participacion', RelationMap::ONE_TO_MANY, array('id' => 'personaje_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PersonajeTableMap
