<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/30 10:21:46

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=starwars;host=localhost',
  'username' => 'user',
  'password' => 'password',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
