<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/12/12 11:55:32
$this->security = array (
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 'preferredPermission',
  ),
);
