<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/12/12 11:55:32
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
