<?php


/**
 * Skeleton subclass for representing a row from the 'raza' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/07/12 18:29:57
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Raza extends BaseRaza {
    public function __toString() { return $this->getName(); }
    public function setName($name)
    {
    parent::setName($name);
    $this->setSlug(TodoRazas::slugify($name));
    }    
} // Raza
